import type { Metadata } from 'next';
// import { Inter } from "next/font/google";
import { Inter as FontSans } from 'next/font/google';
import '@/styles/globals.css';
import '@/styles/styles.scss';

import { cn } from '@/lib/utils';
import Header from '@/components/layout/Header';
import Provider from '@/queryClient/Providers';
import { AlertProvider } from './contexts/AlertContext';
import AlertCustom from '@/components/Alert/AlertCustom';
import { LoadingProvider } from './contexts/LoadingContext';
import LoaderSpinner from '@/components/Loaders/LoaderSpinner';
import { GlobalProvider } from '@/globalContext/GlobalContext';
import { ThemeProvider } from '@/components/theme-provider';

// const inter = Inter({ subsets: ["latin"] });

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <GlobalProvider>
              <AlertProvider>
                <LoadingProvider>
                  <>
                    <Header />
                    <AlertCustom />
                    <LoaderSpinner />
                    <div className='container flex-1 items-start'>
                      {children}
                    </div>
                  </>
                </LoadingProvider>
              </AlertProvider>
            </GlobalProvider>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
